name: Deploy React App on Sporepress Server

on:
  push:
    branches:
      - "react-app-demo-v4" # Change this to the branch you want to monitor
    paths-ignore: # Ignore files that don't need redeployment
      - "README.md"
  workflow_dispatch: # Allow manual trigger from GitHub Actions

jobs:
  deploy:
    # Trigger on specific commit message
    if: contains(github.event.head_commit.message, 'deploy:')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SPOREPRESS_PRIVATE_KEY }}" > private_key.pem   # Create private key file
          chmod 600 private_key.pem                                        # Set permissions to make it secure
        env:
          PRIVATE_KEY: ${{ secrets.SPOREPRESS_PRIVATE_KEY }}

      - name: Deploy Docker Container
        env:
          HOST: ${{ secrets.SPOREPRESS_HOST }} # Use SPOREPRESS_HOST secret here
          USER: ${{ secrets.SPOREPRESS_USER }} # Use SPOREPRESS_USER secret here
        run: |
          # SSH into the server and rebuild/restart the Docker container
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
          set -e  # Exit on any error

          # Ensure Git is configured to use SSH
          git config --global url."git@github.com:".insteadOf "https://github.com/"

          # Navigate to the project directory
          cd /home/openhome-frontend

          # Pull the latest changes from the GitHub repo
          git pull origin react-app-demo-v4

          # Stop and remove the old container
          docker stop openhome-app-container || true
          docker rm openhome-app-container || true

          # Clean up unused Docker resources
          docker system prune -f --volumes

          # Build the Docker container again
          docker build -f dockerfile.sporepress -t openhome-app .

          # Run the newly built container with access to certs, media, static folders in dashboard as volumes
          docker run -d \
            -p 80:80 \
            -p 443:443 \
            -v /home/certs:/etc/nginx/certs \
            -v /home/openhome-dashboard/static/staticfiles:/home/staticfiles \
            -v /home/openhome-dashboard/media:/home/media \
            --network="host" \
            --name openhome-app-container \
            openhome-app

          EOF

      - name: Clean up SSH Key
        run: |
          rm -f private_key.pem
